name: 11775-hw2
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch::pytorch=1.10
  - pytorch::torchvision
  - jupyterlab
  - scikit-learn
  - pandas
  - autopep8
  - pip
  - pip:
    - opencv-python>=4.5
    - pytorch_lightning>=1.5
    - av>=8.0
    - py-turbo>=0.6
